apiVersion: v1
kind: Service
metadata:
  name: php-app
  namespace: woodbridge-designs
spec:
  selector:
    app: php-app
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: fpm
