apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-app
  namespace: woodbridge-designs
data:
  app.conf: |
    server {
        listen 80 default_server;
        server_name woodbridge-designs.local;

        root /var/www/html/public;
        index index.php index.html;
        autoindex off;
        charset utf-8;

        add_header X-Frame-Options SAMEORIGIN;
        add_header X-XSS-Protection "1; mode=block";
        add_header X-Content-Type-Options nosniff;

        error_page 404 /index.php;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_pass php-app.woodbridge-designs:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;

            # Timeouts
            fastcgi_read_timeout 300;
            fastcgi_send_timeout 300;

            # Buffering
            fastcgi_buffers 8 16k;
            fastcgi_buffer_size 32k;

            fastcgi_intercept_errors on;
            fastcgi_hide_header X-Powered-By;
        }

        location = /healthz {
            access_log off;
            return 200 'healthy';
            add_header Content-Type text/plain;
        }

        location ~ /\.(?!well-known).* {
            deny all;
        }

        location ~ /\.ht {
            deny all;
        }
    }
