apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: woodbridge-code
  namespace: woodbridge-designs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
